name: Publish Nightly for Jellyfin

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  jellyfin:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Dotnet
      run: dotnet build --no-restore --configuration=Release
    - name: "Flag as nightly in build.yaml"
      uses: fjogeleit/yaml-update-action@v0.10.0
      with:
        valueFile: 'build.yaml'
        propertyPath: 'version'
        value: "0.0.0.9000"
        commitChange: false
        updateFile: true
    # - name: Rename Files
    #   run: |-
    #     pushd Jellyfin.Plugin.Stash/bin/Release/net6.0/
    #     mv Stash.dll Jellyfin.Plugin.Stash.dll
    #     mv Stash.pdb Jellyfin.Plugin.Stash.pdb
    #     ls -l
    #     popd
    - name: "JPRM: Build"
      id: jrpm
      uses: oddstr13/jellyfin-plugin-repository-manager@b9e92867a6aa279d611a5ea80cf61f6358838c39
      with:
        version: "0.0.0.9000"
        verbosity: debug
        path: .
        dotnet-target: "net6.0"
        output: _dist
    - name: Prepare GitHub Release assets
      run: |-
        pushd _dist
        for file in ./*.zip; do
          md5sum ${file#./} >> ${file%.*}.md5
          sha256sum ${file#./} >> ${file%.*}.sha256
        done
        ls -l
        popd
    - name: Publish output artifacts
      id: publish-assets
      uses: softprops/action-gh-release@50195ba7f6f93d1ac97ba8332a178e008ad176aa
      with:
          prerelease: false
          fail_on_unmatched_files: true
          tag_name: latest_jellyfin
          name: Development Build for Jellyfin
          files: |
            _dist/*
            build.yaml
          body: |
            Nightly build.
            Add https://raw.githubusercontent.com/${{github.repository}}/manifest-release/manifest.json
            to your repositories to use.
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish Plugin Manifest
      uses: Kevinjil/jellyfin-plugin-repo-action@a7832ecc44c6b1a45d531970f6647b8682b005b8
      with:
        ignorePrereleases: true
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        pagesBranch: manifest-release
        pagesFile: manifest.json
